# Generated by Django 4.0.4 on 2022-06-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('config_file', models.FilePathField(path='/home/jamedeus/git/micropython-smarthome/config')),
            ],
        ),
    ]
