# Generated by Django 4.0.4 on 2022-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file', models.FilePathField(path='/home/jamedeus/git/micropython-smarthome/config')),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
