# Generated by Django 4.0.4 on 2022-08-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0002_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
