# Generated by Django 4.0.4 on 2022-09-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0003_wificredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
