# Generated by Django 4.0.4 on 2023-01-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0004_node_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='config',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='node_configuration.node'),
        ),
        migrations.AlterField(
            model_name='config',
            name='config_file',
            field=models.FilePathField(path=None),
        ),
        migrations.AlterField(
            model_name='node',
            name='config_file',
            field=models.FilePathField(path=None),
        ),
    ]
