# Generated by Django 4.0.4 on 2023-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0005_remove_config_uploaded_config_config_config_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='config_file',
        ),
        migrations.RemoveField(
            model_name='node',
            name='config_file',
        ),
        migrations.AlterField(
            model_name='config',
            name='config',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='config',
            name='filename',
            field=models.CharField(max_length=50),
        ),
    ]
