# Generated by Django 4.0.4 on 2023-04-15 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0006_remove_config_config_file_remove_node_config_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='filename',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='floor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='node',
            name='friendly_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
