# Generated by Django 4.0.4 on 2023-05-04 05:42

import django.core.validators
from django.db import migrations, models
import node_configuration.models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0007_alter_config_filename_alter_node_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
                ('timestamp', node_configuration.models.TimeStampField(max_length=5, validators=[django.core.validators.RegexValidator(message='Timestamp format must be HH:MM (no AM/PM).', regex='^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')])),
            ],
        ),
    ]
