# Generated by Django 4.0.4 on 2023-05-08 07:34

from django.db import migrations


# Pre-populate sunrise and sunset entries so they will be available
# in schedule rules dropdown (options loaded from database)
def add_sunrise_sunset_keywords(apps, schema_editor):
    ScheduleKeyword = apps.get_model('node_configuration', 'ScheduleKeyword')
    ScheduleKeyword.objects.get_or_create(keyword='sunrise', defaults={'timestamp': '06:00'})
    ScheduleKeyword.objects.get_or_create(keyword='sunset', defaults={'timestamp': '18:00'})


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0008_schedulekeyword'),
    ]

    operations = [
        migrations.RunPython(add_sunrise_sunset_keywords),
    ]
