# Generated by Django 4.2.1 on 2023-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node_configuration", "0010_auto_20230526_0246"),
    ]

    operations = [
        migrations.CreateModel(
            name="GpsCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display", models.TextField()),
                ("lat", models.DecimalField(decimal_places=5, max_digits=8)),
                ("lon", models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
