# Generated by Django 4.2.2 on 2023-06-16 02:44

from django.db import migrations


def add_min_max_brightness(apps, schema_editor):
    Config = apps.get_model('node_configuration', 'Config')
    for config in Config.objects.all():
        for i in config.config:
            # Skip irrelevant instances, instances that already have min/max attributes
            if not i.startswith('device'):
                continue
            if not config.config[i]['_type'] in ['dimmer', 'bulb', 'pwm', 'wled']:
                continue
            if 'min_bright' in config.config[i].keys() and 'max_bright' in config.config[i].keys():
                continue

            # Set min/max to default value for each type
            if config.config[i]['_type'] in ['dimmer', 'bulb']:
                config.config[i]['min_bright'] = 1
                config.config[i]['max_bright'] = 100
            if config.config[i]['_type'] == 'pwm':
                config.config[i]['min_bright'] = 1
                config.config[i]['max_bright'] = 1023
            if config.config[i]['_type'] == 'wled':
                config.config[i]['min_bright'] = 1
                config.config[i]['max_bright'] = 255
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("node_configuration", "0011_gpscoordinates"),
    ]

    operations = [
        migrations.RunPython(add_min_max_brightness)
    ]
