# Generated by Django 4.0.4 on 2023-10-14 08:38

import json
from django.db import migrations
from django.conf import settings


# Replace all "min_bright" attributes with "min_rule"
# Replace all "max_bright" attributes with "max_rule"
def fix_config_rule_limits(apps, schema_editor):
    Config = apps.get_model('node_configuration', 'Config')
    for config in Config.objects.all():
        for i in config.config:
            if not i.startswith('device'): continue
            if not config.config[i]['_type'] in ['pwm', 'dimmer', 'bulb', 'wled']: continue

            config.config[i]['min_rule'] = config.config[i]['min_bright']
            config.config[i]['max_rule'] = config.config[i]['max_bright']
            del config.config[i]['min_bright']
            del config.config[i]['max_bright']
        config.save()


def update_config_on_disk(apps, scheda_editor):
    Config = apps.get_model('node_configuration', 'Config')
    for config in Config.objects.all():
        with open(settings.CONFIG_DIR + config.filename, 'w') as file:
            json.dump(config.config, file)


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0012_add_min_max_bright_attributes'),
    ]

    operations = [
        migrations.RunPython(fix_config_rule_limits),
        migrations.RunPython(update_config_on_disk)
    ]
