# Generated by Django 4.0.4 on 2023-10-14 08:38

import json
from django.db import migrations
from django.conf import settings


# Replace "relay" type with "tasmota-relay"
def fix_relay_type(apps, schema_editor):
    Config = apps.get_model('node_configuration', 'Config')
    for config in Config.objects.all():
        for i in config.config:
            if not i.startswith('device'): continue
            if not config.config[i]['_type'] == 'relay': continue

            config.config[i]['_type'] = 'tasmota-relay'
        config.save()


def update_config_on_disk(apps, scheda_editor):
    Config = apps.get_model('node_configuration', 'Config')
    for config in Config.objects.all():
        with open(settings.CONFIG_DIR + config.filename, 'w') as file:
            json.dump(config.config, file)


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0013_auto_20231014_0138'),
    ]

    operations = [
        migrations.RunPython(fix_relay_type),
        migrations.RunPython(update_config_on_disk)
    ]
