# Generated by Django 4.2.3 on 2024-07-21 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0015_auto_20231109_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='floor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-999), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
