# Generated by Django 4.2.14 on 2024-07-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0016_alter_node_floor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WifiCredentials',
        ),
    ]
