# Generated by Django 4.2.14 on 2024-07-30 04:04

from django.db import migrations


def remove_wifi_credentials(apps, schema_editor):
    '''Remove the wifi key from config field of each Config model entry.
    Config files no longer contain wifi credentials for security reasons
    (replaced with wifi_credentials.json created during initial setup).
    '''
    Config = apps.get_model('node_configuration', 'Config')
    for config in Config.objects.all():
        try:
            del config.config['wifi']
            config.save()
        except KeyError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('node_configuration', '0017_delete_wificredentials'),
    ]

    operations = [
        migrations.RunPython(remove_wifi_credentials)
    ]
