version: "3.5"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/pi/docker/nginx:/etc/nginx/certs
    restart: unless-stopped
    networks:
      - reverse_proxy

  smarthome:
    image: micropython-smarthome:0.7
    container_name: smarthome
    hostname: smarthome
    environment:
      # Reverse proxy domain name
      - VIRTUAL_HOST=smarthome.lan
    volumes:
      # Persistent storage between sessions
      - smarthome-data:/repo
      # Settings (django key, allowed hosts, etc)
      - /home/pi/docker/smarthome/settings.json:/repo/settings.json
      # Optional: Generated config files will be written here if present
      - /home/pi/docker/smarthome/config:/repo/config
    ports:
      - 8456:8456
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    name: reverse_proxy
    driver: bridge

volumes:
  smarthome-data:
