# Generated by Django 4.0.4 on 2023-01-24 05:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='name',
            field=api.models.NameField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='macro',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='non_empty_title'),
        ),
    ]
