#!/bin/sh

# This hook creates a tag if any files included in the firmware have changed.
# Pushing the tag creates a CI/CD job that builds and releases the firmware.


# Skip if not on master branch
if [ "$(git branch --show-current)" != "master" ]; then
    exit
fi


# Check if firmware files are includes in commit
FIRMWARE_FILES=$(git diff --name-only HEAD^ HEAD | grep -E "^(devices/|sensors/|lib/|core/|firmware/|lib/|setup.html)")

# Remove readme files (not included in firmware, shouldn't trigger release)
FIRMWARE_FILES=$(echo "$FIRMWARE_FILES" | grep -v "readme.md")

if [ -n "$FIRMWARE_FILES" ]; then
    # Increment most-recent tag
    LAST_TAG="$(git tag | sort -V | tail -n 1)"
    NEW_TAG="$(echo "$LAST_TAG" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)"

    # Tag new commit (triggers firmware build job)
    git tag "$NEW_TAG"
fi
