#!/bin/sh

# Pre-commit actions:
# - Check if static files are part of the commit and automatically
#   update static cache version (forces PWA clients to refresh
#   cache and download new version)
#
# - Check if desktop-integration files are part of commit, update
#   micropython-smarthome-integration.zip (downloadable from
#   overview page in django frontend)


# Skip if not on master branch
if [ "`git branch --show-current`" != "master" ]; then
    exit
fi

# Check if static files are included in commit
STATIC_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E "^(frontend/api/static/api/|frontend/node_configuration/static/node_configuration/)")

# Check if desktop integration files are included in commit
DESKTOP_INTEGRATION=$(git diff --cached --name-only --diff-filter=d | grep -E "^(desktop-integration/)")


if [ ! -z "$STATIC_FILES" ]; then
    # Get short hash of last commit (used as PWA version number)
    COMMIT_HASH=$(git rev-parse --short HEAD)

    # Overwrite old staticCacheName to force client cache refresh
    sed -i -E "s/^var staticCacheName = \"django-pwa-v.*$/var staticCacheName = \"django-pwa-v${COMMIT_HASH}\";/" frontend/webapp/serviceworker.js

    # Commit new static cache version
    git add frontend/webapp/serviceworker.js
fi


if [ ! -z "$DESKTOP_INTEGRATION" ]; then
    # Zip current contents of desktop-integration, overwrite old bundle in static dir
    zip -r frontend/node_configuration/static/node_configuration/micropython-smarthome-integration.zip desktop-integration/

    # Commit new desktop-integration bundle, pipeline will build into new docker images
    git add frontend/node_configuration/static/node_configuration/micropython-smarthome-integration.zip
fi
